config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  
  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
    belongs_to :user
    belongs_to :category
    
  has_attached_file :book_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :books
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :books
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :find_book, only: [:show, :edit, :update, :destroy]
    
    def index
        if params[:category].blank?
        @books = Book.all.order("created_at DESC")
        else
        @category_id = Category.find_by(name: params[:category]).id
        @books = Book.where(:category_id => @category_id).order("created_at DESC")
        end
    end
    
    def show
    end
    
    def new
        @book = current_user.books.build
        @categories = Category.all.map{ |c| [c.name, c.id] }
    end
    
    def create
        @book = current_user.books.build(book_params)
        @book.category_id = params[:category_id]
        
        if @book.save
            redirect_to root_path
        else
            render 'new'
        end
    end
    
    def edit
        @categories = Category.all.map{ |c| [c.name, c.id] }
    end
    
    def update
        @book.category_id = params[:category_id]
        if @book.update(book_params)
            redirect_to book_path(@book)
        else
            render 'edit'
        end
    end
    
    def destroy
        @book.destroy
        redirect_to root_path
    end
    
    private
        def book_params
           params.require(:book).permit(:title, :description, :author, :category_id, :book_img) 
        end
        
        def find_book
            @book = Book.find(params[:id])
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book  do |f| %>
  <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
  <%= f.file_field :book_img %>
  <%= f.input :title, label: "Book title" %>
  <%= f.input :description %>
  <%= f.input :author %>
  <%= f.button :submit %>
<% end %>

<!-- , :html => { multipart => true } -->

app/views/books/edit.html.erb
<h1>Edit book</h1>

<%= simple_form_for @book do |f| %>
  <%= f.select :category_id, @categories %>
  <%= f.file_field :book_img %>
  <%= f.input :title, label: "Book title" %>
  <%= f.input :description %>
  <%= f.input :author %>
  <%= f.button :submit %>
<% end %>

<!-- , :html => { multipart => true }  -->

app/views/books/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @books.count == 0 %>
    <h1>There are no books currently in this category</h1>
<% else %>

    <div class="row">
        
    <% @books.each do |book| %>
    <div class="col-md-3">
        <a href="/books/<%= book.id %>">
            <%= image_tag book.book_img.url(:book_index), class: "book" %>
        </a>
    </div>
    
    <% end %>
    
    </div>
<% end %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<div class="row">
    
    <div class="col-md-4">
        <%= image_tag @book.book_img.url(:book_show), clas: "book-show" %>
    </div>
    
    <div class="col-md-8">
        <h2><%= @book.title %></h2>
        <h3><%= @book.author %></h3>
        <p><%= @book.description %></p>
    </div>
</div>

<div class="row">
    
    <div class="col-md-4">
        <!-- Where the reviews/ratings will do -->
    </div>
    
</div>
<%= link_to "Back", root_path %>

<% if user_signed_in? %>

    <% if @book.user_id == current_user.id %>
    <%= link_to "Edit", edit_book_path(@book) %>
    <%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-default">
      
      <div class="container">
        
        <div class="navbar-header">
          <%= link_to "Book Review", root_path, class: "navbar-brand" %>
        </div>
        
        <ul class="nav navbar-nav">
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          
          <% if user_signed_in? %>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Log in", new_user_session_path %></li>
          <% end %>
        </ul>
        
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" 
              role="button" aria-expanded="false">Categories <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <% Category.all.each do |category| %>
                <li class="<%= 'active' if params[:category] == category.name %>">
                  <%= link_to category.name, books_path(category: category.name), class: "link" %>
                </li>
                <% end %>
              </ul>
            </li>
            
            
            
            
            <% if user_signed_in? %>
              <li><%= link_to "Add Book", new_book_path %></li>
            <% end %>
          </ul>
          
        
        
      </div>
      
    </nav>
    
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>
  </div>
  
</body>
</html>